[[session]]
name = "tmux config"
path = "~/dotfiles/"
startup_command = "nvim .tmux.conf"
preview_command = "bat --color=always ~/dotfiles/.tmux.conf"

[[session]]
name = "sesh config"
path = "~/dotfiles/"
startup_command = "nvim ./.config/sesh/sesh.toml"
preview_command = "bat --color=always ~/dotfiles/.config/sesh/sesh.toml"

[[session]]
name = "nvim config"
path = "~/dotfiles/.config/nvim/"
startup_command = "nvim ."
preview_command = "bat --color=always ~/dotfiles/.config/nvim/"

# [[session]]
# name = "Example"
# path = "Directory"
# startup_command = "cd directory && tmux rename-window window-1 && tmux split-window -v -l 18 'command' & tmux select-pane -U && nvim ."
# windows = [ "window-2" ]
#
# [[window]]
# name = "window-2"
# startup_script = "cd directory-2 && tmux split-window -v -l 18 -t Example:window-2 'command' & tmux select-pane -U && nvim ."
#
